version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo_train_tickets
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: train_tickets_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
